- client_config_backend: file
- client_config_file: /Users/user/Documents/Automations/update_pass_DB/client_secrets.json
- save_credentials: False
- oauth_scope: ['https://www.googleapis.com/auth/drive']